#!/usr/bin/env node
'use strict';

// CLI for mcp-convention-gate — init (install hook + config), status, check.
// Usage:
//   npx mcp-convention-gate init     — install git hook + .gate-config.json
//   npx mcp-convention-gate status   — show current gate status
//   npx mcp-convention-gate check    — run the pre-commit check manually

const fs = require('fs');
const path = require('path');

// ── Find repo root ───────────────────────────────────────────────────────────

function findRepoRoot(startDir) {
  let dir = startDir || process.cwd();
  for (let i = 0; i < 20; i++) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

// ── Init command ─────────────────────────────────────────────────────────────

function cmdInit() {
  const repoRoot = findRepoRoot();
  if (!repoRoot) {
    console.error('Error: not inside a git repository.');
    process.exit(1);
  }

  const hooksDir = path.join(repoRoot, '.git', 'hooks');
  const hookDest = path.join(hooksDir, 'pre-commit');
  const configDest = path.join(repoRoot, '.gate-config.json');
  const hookSource = path.join(__dirname, 'hook.js');

  // 1. Install pre-commit hook
  if (fs.existsSync(hookDest)) {
    const existing = fs.readFileSync(hookDest, 'utf8');
    if (existing.includes('convention-gate')) {
      console.log('  Hook already installed, updating...');
    } else {
      // Back up existing hook
      const backup = hookDest + '.backup';
      fs.copyFileSync(hookDest, backup);
      console.log(`  Existing hook backed up to ${path.basename(backup)}`);
    }
  }

  // Write a hook script that calls our hook.js
  const hookScript = `#!/usr/bin/env node
// Auto-generated by mcp-convention-gate init — do not edit manually
// This hook enforces development convention gates before allowing commits.
// NOTE: call .main() explicitly — hook.js guards main() behind
// \`require.main === module\`, which is false when loaded via this wrapper.
require(${JSON.stringify(hookSource)}).main();
`;

  if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir, { recursive: true });
  fs.writeFileSync(hookDest, hookScript, { mode: 0o755 });
  console.log('  ✓ Pre-commit hook installed');

  // 2. Create config file if it doesn't exist
  if (!fs.existsSync(configDest)) {
    const config = {
      enabled: true,
      required_gates: [
        'spec-reviewer', 'architect', 'code-reviewer', 'security-auditor',
        'test-writer', 'qa-acceptance', 'debugger', 'docs-writer', 'ux-evaluator',
      ],
      _comment: 'Edit required_gates to customize which agent reviews are mandatory.',
    };
    fs.writeFileSync(configDest, JSON.stringify(config, null, 2) + '\n');
    console.log('  ✓ .gate-config.json created');
  } else {
    console.log('  ✓ .gate-config.json already exists');
  }

  // 3. Add .gate-store.json to .gitignore if not already there
  const gitignorePath = path.join(repoRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf8');
    if (!gitignore.includes('.gate-store.json')) {
      fs.appendFileSync(gitignorePath, '\n# Convention gate runtime state\n.gate-store.json\n');
      console.log('  ✓ .gate-store.json added to .gitignore');
    }
  }

  // 4. Create MCP config snippet
  const mcpConfigPath = path.join(repoRoot, '.vscode', 'mcp.json');
  if (!fs.existsSync(mcpConfigPath)) {
    const mcpDir = path.join(repoRoot, '.vscode');
    if (!fs.existsSync(mcpDir)) fs.mkdirSync(mcpDir, { recursive: true });

    const serverPath = path.join(__dirname, 'server.js');
    const mcpConfig = {
      servers: {
        'convention-gate': {
          command: 'node',
          args: [serverPath],
          env: { MCP_GATE_STORE_PATH: path.join(repoRoot, '.gate-store.json') },
        },
      },
    };
    fs.writeFileSync(mcpConfigPath, JSON.stringify(mcpConfig, null, 2) + '\n');
    console.log('  ✓ .vscode/mcp.json created');
  } else {
    console.log('  ⚠ .vscode/mcp.json already exists — add convention-gate server manually');
    console.log(`    Server path: ${path.join(__dirname, 'server.js')}`);
  }

  console.log('\n  Setup complete. Convention gates are now enforced on commit.');
  console.log('  Use the MCP tools (create_gate_session, register_gate) to register reviews.');
  console.log('  The pre-commit hook will block commits until all gates pass.\n');
}

// ── Status command ───────────────────────────────────────────────────────────

function cmdStatus() {
  const repoRoot = findRepoRoot();
  if (!repoRoot) {
    console.error('Error: not inside a git repository.');
    process.exit(1);
  }

  const storePath = process.env.MCP_GATE_STORE_PATH ||
    path.join(repoRoot, '.gate-store.json');

  // Load config
  const configPath = path.join(repoRoot, '.gate-config.json');
  let required;
  try {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    required = config.required_gates;
  } catch (e) {
    required = [
      'spec-reviewer', 'architect', 'code-reviewer', 'security-auditor',
      'test-writer', 'qa-acceptance', 'debugger', 'docs-writer', 'ux-evaluator',
    ];
  }

  // Load store
  let sessions;
  try {
    sessions = JSON.parse(fs.readFileSync(storePath, 'utf8'));
  } catch (e) {
    console.log('No gate sessions found. Create one with create_gate_session.');
    return;
  }

  const active = sessions.filter(s => !s.committed);
  if (active.length === 0) {
    console.log('No active gate sessions. Create one with create_gate_session.');
    return;
  }

  for (const session of active) {
    const passed = new Set(
      (session.gates || []).filter(g => g.result === 'pass').map(g => g.name)
    );
    const failed = (session.gates || []).filter(g => g.result === 'fail').map(g => g.name);
    const missing = required.filter(g => !passed.has(g));
    const allowed = missing.length === 0 && failed.length === 0;

    console.log(`\nSession: ${session.id}`);
    console.log(`  Description: ${session.description}`);
    console.log(`  Created: ${session.createdAt}`);
    console.log(`  Commit allowed: ${allowed ? 'YES' : 'NO'}`);
    console.log(`  Gates: ${passed.size}/${required.length} passed`);
    if (missing.length) console.log(`  Missing: ${missing.join(', ')}`);
    if (failed.length) console.log(`  Failed: ${failed.join(', ')}`);
  }
}

// ── Check command (dry-run of pre-commit hook) ───────────────────────────────

function cmdCheck() {
  const { main } = require('./hook.js');
  main();
}

// ── CLI dispatch ─────────────────────────────────────────────────────────────

const command = process.argv[2];

switch (command) {
  case 'init':
    console.log('\n  mcp-convention-gate — initializing...\n');
    cmdInit();
    break;
  case 'status':
    cmdStatus();
    break;
  case 'check':
    cmdCheck();
    break;
  case '--help':
  case '-h':
  case undefined:
    console.log(`
  mcp-convention-gate — enforceable development convention gates

  Commands:
    init      Install git pre-commit hook and create config
    status    Show current gate session status
    check     Dry-run the pre-commit gate check

  The MCP server runs separately (via VS Code or Claude Desktop config).
  See README.md for setup instructions.
`);
    break;
  default:
    console.error(`Unknown command: ${command}. Run with --help for usage.`);
    process.exit(1);
}
